spring:
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/tams?characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
  # JPA配置 - 禁用自动配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

logging:
  level:
    com.lhd.tams: info

springdoc:
  api-docs:
    enabled: false

tams:
  logging:
    path: /logs/tams/logs

# JWT 配置
jwt:
  secret-key: x7H$2pL9&qW8zRvE1tY6uIoP3aS5dFgHjK4lMnBvCxZ  # 生产环境密钥
  expiration-time: 864000000  # Token 过期时间（毫秒），10 天
