spring:
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/timetable?characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
  # JPA配置已移除，使用MyBatis-Plus

logging:
  level:
    com.jvav.timetable: info

springdoc:
  api-docs:
    enabled: false

jvav:
  logging:
    path: ./logs/jvav/logs

# JWT 配置
jwt:
  secret-key: Q2hpbmFfU2VjcmV0X0tleV9Gb3JfSlcudGVzdF9iYXNlNjQ=  # 生产环境密钥
  expiration-time: 864000000  # Token 过期时间（毫秒），10 天
