
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timetable?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "@Abc12345"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10


  mail:
    host: smtp.qq.com
    port: 587
    username: 2139728203@qq.com
    password: zagzwnsbvrvcicfg
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.lhd.tams: debug

springdoc:
  api-docs:
    enabled: true

tams:
  logging:
    path: ./logs/tams/logs

    # 新增 JWT 配置
jwt:
  secret-key: Q2hpbmFfU2VjcmV0X0tleV9Gb3JfSlcudGVzdF9iYXNlNjQ=  # 替换为你生成的密钥
  expiration-time: 864000000  # Token 过期时间（毫秒），例如 10 天